spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mvc:
    view:
      prefix: /
      suffix: .html
# mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bpm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
#    username: test
#    password: 111111
# oracle
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.128.108.242:1521:orcl
#    username: gvmbpm
#    password: gvmbpm
#    type: com.alibaba.druid.pool.DruidDataSource
  tomcat:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  redis:
    database: 0
    host: 10.128.108.12
    port: 6379
    password: Cic@123456#redis
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
  application:
    name: gvmbpm-lhx
  zipkin:
    base-url: http://10.128.108.12:9411
    sender:
      type: web
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  profiles:
    active: dev
  activiti:
    check-process-definitions: false

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml

#  type-aliases-package: com.cic.common.model.*
#  type-handlers-package: com.cic.common.handler
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cic.common.model
  type-handlers-package: com.cic.common.handler
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


## 发现服务
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${cic.server.ip}:${cic.server.port}/eureka
#  instance:
#    prefer-ip-address: true
#    health-check-url-path: /actuator/health
#过1s向服务端发送心跳
#    lease-renewal-interval-in-seconds: 1
#超过2s服务端未收到心跳，认为该服务dead
#    lease-expiration-duration-in-seconds: 2
#服务自我保护，在非server服务处注掉
#  server:
#    enable-self-preservation: false

# 中心服务ip端口
cic:
  server:
    ip: 10.128.108.12
    port: 8050
  security:
    filter: /**
    zyLost: /api/**
    local:
#      host: http://ROUTES-TEST
      getOnceVerificationCenterIpAddrUrl: http://verification-center-test/getOnceVerificationIpAddr
      getPrivilegesUrl: http://user-resource-test/rest/privilegeService/v1/privileges/service?serviceName=%s

rest:
  read:
    timeout: 60000
  connect:
    timeout: 60000

baiduApi:
  routeMatrix:
      urlTemplate: http://api.map.baidu.com/routematrix/v2/driving?origins=%s&destinations=%s&output=json&ak=%s
      transformate: http://api.map.baidu.com/geoconv/v1/?coords=%s&from=%s&to=%s&ak=%s&output=json
      ak: vR31WdEe7MUHP659bD3q3MKCQU9tZf5T
#      ak: FI3aXG0ICe95W9xin2uTwPmgQOb2kH95

targetOrigin:
  localhost:
    url: http://localhost:8000/
  use:
    url: http://10.128.108.242:8001/
# 发现服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://${cic.server.ip}:${cic.server.port}/eureka
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30